sudo: required

services:
  - docker





before_install:
  - docker pull simexp/niak_dependency
  - docker run -it --privileged -v /home/travis/SIMEXP:/home/travis/SIMEXP simexp/niak_dependency /bin/bash --login -ic "cd /home/travis/SIMEXP; octave --eval 'addpath(genpath(pwd));[pipe,opt,status] = niak_test_all(struct(),struct('psom',struct('mode_pipeline_manager','session','mode','background','max_queued',2,'flag_pause',false))); system('cat result/report_test_re    gression_fmripreproc_demoniak.csv'), exit(status)   '"


script:
  - octave --eval "[pipe,opt,status] = niak_test_all(struct(),struct('psom',struct('mode_pipeline_manager','session','mode','background','max_queued',2,'flag_pause',false))); system('cat result/report_test_regression_fmripreproc_demoniak.csv'), exit(status)"

notifications:
  email: false
  slack: simexp:eFh4jwo2RWWvSoafeVx9xzoU
