script:
  - ls -lha /home/travis/.gnupg/gpg.conf
  - gpg --keyserver pgpkeys.mit.edu --recv-key  8B48AD6246925553      
  - gpg -a --export 8B48AD6246925553 | sudo apt-key add -

notifications:
  email: false
