before_script:
  - sudo apt-add-repository ppa:octave/stable --yes
  - sudo apt-get update -y
  - sudo apt-get install octave -y
  - sudo apt-get install liboctave-dev -y
  - git clone https://github.com/SIMEXP/psom.git
  - echo $PWD
  - ls
script:
  - octave demos/run_test.m

notifications:
  email: false
