script:
  - gpg --keyserver pgpkeys.mit.edu --recv-key  8B48AD6246925553      
  - gpg -a --export 8B48AD6246925553 | sudo apt-key add -
  # Add the backports to the sources
  - sudo apt-get install python-software-properties
  - sudo add-apt-repository "deb http://http.debian.net/debian wheezy-backports main"
  # Update the sources again
  - sudo apt-get update
  - sudo apt-get -t wheezy-backports install "octave" -y
