script:
  # Add the backports to the sources
  - sudo apt-get install python-software-properties
  - sudo apt-add-repository ppa:octave/stable
  - sudo apt-get update
  - sudo apt-get install octave
  
