before_script:
  - sudo apt-add-repository ppa:octave/stable --yes
  - sudo apt-get update -y
  - sudo apt-get install octave -y
  - sudo apt-get install liboctave-dev -y
  - sudo demos/run_install.m
script:
  - octave demos/run_install.m

notifications:
  email: false
