version: 2
jobs:
  build:
    working_directory: /niak
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --update openssl
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/app.tar | true
      - run:
          name: Build application Docker image
          command: |
            docker build --cache-from=app -t bids/niak .
      - run:
          name: Set sample data
          command: |
            if [[ ! -e "/caches/bids_dataset" ]]; then
              mkdir -p /caches/sample_test
              wget -c -P /caches https://github.com/BIDS-Apps/niak/releases/download/data_for_test/bids_dataset.tgz
              cd /caches
              tar -zxvf bids_dataset.tgz
              rm bids_dataset.tgz
            fi
      - run:
          name: Run tests
          command: |
            mkdir -p /outputs
            chmod 777  /outputs
            [ ! "$(docker ps -a | grep data)" ] && docker create -v /bids_dataset -v  /outputs --name data alpine /bin/true
            docker cp  /caches/bids_dataset data:/
            docker run -it --read-only --volumes-from data bids/niak participant /bids_dataset /outputs --n_thread 2 --participant_label "275"
            docker run -it --read-only --volumes-from data bids/niak group /bids_dataset /outputs --n_thread 2 --participant_label "275"
            docker cp data:/outputs /
            chmod 777 -R /outputs
      - store_artifacts:
          path: /outputs
      - deploy:
          name: Push application Docker image
          command: |
            if [[ "${CIRCLE_BRANCH}" == "master" && -n "${DOCKER_PASS}" ]]; then
              docker login -e ${DOCKER_EMAIL} -u ${DOCKER_USER} -p ${DOCKER_PASS}
              docker push bids/${CIRCLE_PROJECT_REPONAME}:latest
              if [[ -n "${CIRCLE_TAG}" ]]; then
                docker tag bids/${CIRCLE_PROJECT_REPONAME} bids/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_TAG}
                docker push bids/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_TAG};
              fi
            fi
