version: 2
jobs:
  build:
    working_directory: /niak

    machine:
      image: ubuntu-2204:2022.10.2

    steps:
      - checkout

      - restore_cache:
          keys:
            - my_cache

      - run:
          name: Install dependencies
          command: |
            sudo apt-get update && sudo apt-get isntall openssl

      - run:
          name: Build Docker image
          command: |
            if [[ -e ${HOME}/docker/image.tar ]]; \
              then docker load -i ${HOME}/docker/image.tar;
            fi
            git describe --tags --always > version
            docker build -t bids/${CIRCLE_PROJECT_REPONAME,,} .
            mkdir -p ${HOME}/docker
            docker save "bids/${CIRCLE_PROJECT_REPONAME,,}" > ${HOME}/docker/image.tar

      - run:
          name: Set sample data
          command: |
            mkdir -p ${HOME}/data/
            if [[ ! -e "${HOME}/data/bids_dataset" ]]; then
              wget -c -P /caches https://github.com/BIDS-Apps/niak/releases/download/data_for_test/bids_dataset.tgz
              cd ${HOME}/data/
              tar -zxvf bids_dataset.tgz
              rm bids_dataset.tgz
            fi

      - run:
          name: Set sample data
          command: |
            if [[ ! -d ${HOME}/data/bids_dataset ]]; then
              wget -c -O ${HOME}/ds114_test1.tar "https://osf.io/download/zerfq/" && \
              mkdir -p ${HOME}/data && \
              tar xf ${HOME}/ds114_test1.tar -C ${HOME}/data
            fi

      - save_cache:
          key: my_cache
          paths:
            - ~/docker
            - ~/data

      - persist_to_workspace:
          root: /home/circleci
          paths:
            - data/bids_dataset
            - docker/image.tar

  test:
    machine:
      image: ubuntu-2204:2022.10.2

    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          command: |
            docker load -i /tmp/workspace/docker/image.tar

      - run: mkdir -p ${HOME}/outputs && chmod 777 ${HOME}/outputs

      - run:
          name: Run tests participant
          command: |
            docker run -it \
              -v /tmp/workspace/data/bids_dataset:/bids_dataset \
              -v ${HOME}/outputs:/outputs \          
              bids/niak /bids_dataset /outputs participant --n_thread 2 --participant_label "275"
      - run:
          name: Run tests group
          command: |
            docker run -it \
              -v /tmp/workspace/data/bids_dataset:/bids_dataset \
              -v ${HOME}/outputs:/outputs \            
              bids/niak /bids_dataset /outputs group --n_thread 2 --participant_label "275"
            docker cp data:/outputs /
            chmod 777 -R /outputs

      - store_artifacts:
          path: /outputs

  deploy:
    machine:
      image: ubuntu-2204:2022.10.2

    steps:
      - attach_workspace:
          at: /tmp/workspace

      - run: docker load -i /tmp/workspace/docker/image.tar
      - run:
          name: push to dockerhub
          command: |
            if [[ -n "$DOCKER_PASS" ]]; then
              repo_name=`echo  ${CIRCLE_PROJECT_REPONAME} | tr '[:upper:]' '[:lower:]'`
              echo "${DOCKER_PASS}" | docker login -u ${DOCKER_USER} --password-stdin && \
              echo "Pushing to DockerHub bids/${repo_name}:unstable" && \
              docker push bids/${repo_name}:unstable
              if [[ -n "${CIRCLE_TAG}" ]]; then
                echo "Pushing to DockerHub bids/${repo_name}:${CIRCLE_TAG}" && \
                docker push bids/${repo_name}:latest
                docker tag bids/${repo_name} bids/${repo_name}:${CIRCLE_TAG}
                docker push bids/${repo_name}:${CIRCLE_TAG};
              fi
            fi

workflows:
  build-test-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
          filters:
            tags:
              only: /.*/
# VS Code Extension Version: 1.5.1
